---
title: "analysis"
output: pdf_document
---


## Document Options
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE)
```

## Load Packages
```{r}
require(tidyverse)
require(mosaic)
require(lme4)
```

## load dataset
```{r}
load("olympics9.Rdata")
olympicsds <-  olympics9
```

## EDA
```{r}
favstats(olympicsds$medratio)
favstats(olympicsds$tempdiff)
favstats(olympicsds$elevdiff)
tally(~ Season, data = olympicsds)
```


## Simple graphical exploration
```{r}
# Densityplot for elevation difference
olympicsds %>%
  ggplot(aes(x = elevdiff)) + geom_density()

# Densityplot for temperature difference
olympicsds %>%
  ggplot(aes(x = tempdiff)) + geom_density()

# Scatterplot for elevation difference vs medal ratio
olympicsds %>%
  filter(Season == "Summer") %>%
  ggplot(aes(x = elevdiff, y = medratio)) + geom_point()

# Scatterplot for temperature difference vs medal ratio
olympicsds %>%
  filter(Season == "Summer") %>%
  ggplot(aes(x = tempdiff, y = medratio)) + geom_point()
```

## Plot of what we expected to see 
```{r}

########################################
##   Hypothetical (Our Expectation)   ##
########################################

set.seed(10)
elev <- rnorm(30, 0, 200)
temp <- rnorm(30, 0, 4)

expected <- data.frame(elev, temp) %>%
  mutate(dist = sqrt((elev/200)^2 + (temp/4)^2),
         dist = (1 - dist/max(dist)) * 0.3)

ggplot(expected, aes(x = elev, y = temp, col = dist)) + geom_point() +
  labs(x = "Elevation Difference (Meter)", y = "Temperature Difference (Degree Celcius)", title = "Expected Graph: Medal Ratio by Temperature and Elevation Difference", color = "Medal Ratio") + scale_color_gradient(low = "yellow", high = "blue") + 
  geom_vline(xintercept = 0) + geom_hline(yintercept = 0)
```


## Plots exploring effects of elevation/temperature difference on medal ratios
```{r}

#############################
##   Plot from Real Data   ##
#############################

# Create dataset for graphical exploration
olympicsds1 <- olympicsds %>%
  
# Studied Australia, Germany, UK as they are consistent performers  
  filter(region %in% c("Australia", "Germany", "UK")) %>%

# Got rid of winter olympics and rows with missing data
  filter(!is.na(elevdiff), !is.na(tempdiff), Season == "Summer")


olympicsds1 %>%
#Filtered out extreme outliers
  filter(!(elevdiff > 1500)) %>%
  
# Generate plot
  ggplot(aes(x = elevdiff, y = tempdiff)) + geom_point(size = 3.0) + aes(color = medratio)  +  
    facet_wrap(~region, ncol = 4) + theme(legend.position = "right") + labs(title = "") + 
    scale_color_gradient(low = "yellow", high = "blue") + 
    geom_vline(xintercept = 0) + geom_hline(yintercept = 0) +
    labs(x = "Elevation Difference (Meter)", 
         y = "Temperature Difference (Degree Celcius)", 
         title = "Medal Ratio by Temperature and Elevation Difference in 3 Countries", 
         color = "Medal Ratio")
```



## Create dataset used for modelling
```{r}
# Only keep rows that are summer and is not missing temperature and elevation difference  
formodel1 <- olympicsds %>%
  filter(Season == "Summer", !is.na(tempdiff), !is.na(elevdiff))

# Create linear mixed model with clustering as country/region
summary(lmer(medratio ~ tempdiff + elevdiff + (1|region), data = formodel1))
```


#Finding Thresholds for "Similar/Nonsimilar temp/elev"
```{r}
olympicsds%>%
ggplot(aes(x=tempdiff))+
  geom_density()+
  geom_vline(xintercept=-11.41662)+
  geom_vline(xintercept=1.760962)
  

olympicsds%>%
ggplot(aes(x=elevdiff))+
  geom_density()+
  geom_vline(xintercept=-573.75)+
  geom_vline(xintercept=-32.25)


olympicsds2 <- olympicsds %>%
  mutate(sim = ifelse((tempdiff>-11.41662 & tempdiff<1.760962) & (elevdiff>-573.75 & elevdiff<32.25), 1, 0),
         sim = as.factor(sim)) 


olympicsds2 %>%
  filter(region == "Germany") %>%
  ggplot(aes(x = elevdiff, y = medratio, col = Season, )) + geom_point() 
```









