---
title: "PresentationGraphics"
output: pdf_document
---

## Document Options
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE)
```


## Load Packages
```{r}
require(tidyverse)
require(mosaic)
require(lme4)
```


## Graphics representing hypothesis
```{r}

########################################
##   Hypothetical (Our Expectation)   ##
########################################

set.seed(10)
elev <- rnorm(30, 0, 200)
temp <- rnorm(30, 0, 4)

expected <- data.frame(elev, temp) %>%
  mutate(dist = sqrt((elev/200)^2 + (temp/4)^2),
         dist = (1 - dist/max(dist)) * 0.3)

ggplot(expected, aes(x = elev, y = temp, col = dist)) + geom_point() +
  labs(x = "Elevation Difference (Meter)", y = "Temperature Difference (Degree Celcius)", title = "Expected Graph: Medal Ratio by Temperature and Elevation Difference", color = "Medal Ratio") + scale_color_gradient(low = "yellow", high = "blue") + 
  geom_vline(xintercept = 0) + geom_hline(yintercept = 0)
```


## Graphics to explain LMM
```{r}
set.seed(5)
X <- c(runif(50, min = 0, max = 200),0,
       runif(50, min = 0, max = 200),0,
       runif(50, min = 0, max = 200),0,
       runif(50, min = 0, max = 200),0,
       runif(50, min = 0, max = 200),0)
Factors <- c(rep("1",51),rep("2",51),rep("3",51),rep("4",51),rep("5",51))
move <- c(rep(0,51),rep(200,51),rep(50,51),rep(75,51),rep(-25,51))
error <- rnorm(255, 0, 30)
mult <- c(rep(3,51),rep(1.7,51),rep(0.7,51),rep(2,51),rep(2.3,51))


bob <- data.frame(X, Factors, move, error) %>%
  mutate(Y = X * 2 + move + error)

bob %>%
  filter(Factors == "1") %>% 
  ggplot(aes(x = X, y = Y)) + geom_point() + 
  geom_smooth(method = "lm", formula = y ~ x, se = FALSE) +
  labs(title = "Graph with 1 Factor")

ggplot(bob, aes(x = X, y = Y, col = Factors)) + geom_point() + 
  geom_smooth(method = "lm", formula = y ~ x, se = FALSE) + 
  labs(title = "Graph with 5 Factors")
```


